feat: use a timeout to load sync plugin
linuxdeepin/dde-control-center pull request #1271
Opened 2023-03-29 09:32 UTC by Decodetalkers

set 5 sec timeout for if plugin cannot construct

resolve: https://github.com/linuxdeepin/developer-center/issues/3949

遇到了插件初始化无法完成的问题。。如果是真同步的话 -d就永远启动不了了。所以添加超时检查

2023-03-29 09:35 UTC, Decodetalkers commented
当插件走到构造函数了。。里面有个while,那怎么样也退不出来了

2023-03-30 07:19 UTC, justforlxz submitted a review, later dismissed

2023-03-30 07:19 UTC, justforlxz commented on src/frame/pluginmanager.cpp
> +                m_plugins[pair.second] = true;
https://en.cppreference.com/w/cpp/thread/lock_guard

2023-03-30 07:35 UTC, justforlxz requested changes

2023-03-30 07:35 UTC, justforlxz commented on src/frame/pluginmanager.cpp
> +        QThread::sleep(5);
加一个note，解释一下5秒

2023-03-30 07:35 UTC, justforlxz commented on src/frame/pluginmanager.cpp
> +        if (!m_loadAllFinished) {
m_loadAllFinished的作用和 m_plugins 所有的values是true是等同的。

2023-03-30 07:35 UTC, justforlxz commented on src/frame/pluginmanager.h
> +    QMap<QString, bool> m_plugins;
或者考虑换成 QVector，先保存所有要加载的插件名称，加载完成一个就移除一个，剩余的都是timeout的。

2023-03-30 08:09 UTC, justforlxz approved these changes

2023-03-30 08:23 UTC, merged