feat: 控制中心支持用户头像个性化配置
linuxdeepin/dde-control-center pull request #1276
Opened 2023-03-31 02:55 UTC by dengbo11

使用新的账户头像资源,支持用户头像个性化配置

Log: 实现控制中心个性化头像定制功能
Resolve: https://github.com/linuxdeepin/developer-center/issues/3796
Influence: 控制中心账户头像设置

2023-03-31 05:42 UTC, zsien requested changes

2023-03-31 05:42 UTC, zsien commented on src/plugin-accounts/window/accountsmodule.cpp
> +    int y = globalPos.y() + w->height() / 2 - avatarListDialog->height() / 2 + 80;
这里的 -40 和 +80 干嘛的

2023-03-31 05:42 UTC, zsien commented on src/plugin-accounts/window/avatarlistframe.cpp
> +#define EMOJI_DIMENSIONAL_PATH "/var/lib/AccountsService/icons/emoji/dimensional"
用 localstatedir 替换 /var 比较好吧

2023-03-31 05:42 UTC, zsien commented on src/plugin-accounts/window/avatarlistframe.cpp
> +#define FLAT_TYPE "flat"               // 立体头像
注释反了

2023-03-31 09:40 UTC, dengbo11 commented on src/plugin-accounts/window/accountsmodule.cpp
> +    int y = globalPos.y() + w->height() / 2 - avatarListDialog->height() / 2 + 80;
这里当初-40和+80是为了将窗口移动到控制中心窗口中间, 现在之间将设置头像的窗口移动到屏幕的中间位置了

2023-03-31 09:40 UTC, dengbo11 commented on src/plugin-accounts/window/avatarlistframe.cpp
> +#define EMOJI_DIMENSIONAL_PATH "/var/lib/AccountsService/icons/emoji/dimensional"
done

2023-03-31 09:40 UTC, dengbo11 commented on src/plugin-accounts/window/avatarlistframe.cpp
> +#define FLAT_TYPE "flat"               // 立体头像
done

2023-04-03 03:28 UTC, Decodetalkers commented on src/plugin-accounts/window/avatarlistview.cpp
> +    auto index = QRandomGenerator::global()->bounded(20);
index初始化了一次后没有使用啊

2023-04-03 03:46 UTC, wineee commented on archlinux/PKGBUILD
> +        -DCMAKE_INSTALL_LOCALSTATEDIR=/var
@felixonmars Arch 应该在这里指定一下吗？

2023-04-03 03:47 UTC, zsien reviewed
顺便改下 cppcheck 吧

2023-04-03 03:47 UTC, zsien commented on debian/rules
> +	dh_auto_configure -- -DCVERSION=$(DEB_VERSION_UPSTREAM) -DDVERSION=$(PACK_VER) -DCMAKE_INSTALL_LOCALSTATEDIR=/var
debian 会自动传 CMAKE_INSTALL_LOCALSTATEDIR，不需要自己写

2023-04-03 03:47 UTC, zsien commented on CMakeLists.txt
> +add_definitions(-DVarDirectory="${CMAKE_INSTALL_LOCALSTATEDIR}")
应该全大写的蛇形命名吧

2023-04-03 03:47 UTC, zsien commented on src/plugin-accounts/window/avatarlistframe.cpp
> +#define EMOJI_DIMENSIONAL_PATH "lib/AccountsService/icons/emoji/dimensional"
```suggestion
#define EMOJI_DIMENSIONAL_PATH VarDirectory "/lib/AccountsService/icons/emoji/dimensional"
```
顺便，按照规范换成 static const QString 或 QStringLiteral 而不是定义宏更好（其他地方也一样）

2023-04-03 04:27 UTC, wineee commented on CMakeLists.txt
> +add_definitions(-DVarDirectory="${CMAKE_INSTALL_LOCALSTATEDIR}")
有必要传这个变量吗？

2023-04-06 07:36 UTC, Decodetalkers approved these changes

2023-04-06 09:06 UTC, dengbo11 commented
/merge

2023-04-06 09:14 UTC, dengbo11 commented on debian/rules
> +	dh_auto_configure -- -DCVERSION=$(DEB_VERSION_UPSTREAM) -DDVERSION=$(PACK_VER) -DCMAKE_INSTALL_LOCALSTATEDIR=/var
done

2023-04-06 16:11 UTC, BLumia commented
> This pr cannot be merged! (status: blocked)

原本给过 Request changed 的是需要对应的人重新 Approve 才能合并的。

2023-04-07 02:01 UTC, zsien approved these changes

2023-04-07 02:01 UTC, merged