refactor: speed up when read license
linuxdeepin/dde-control-center pull request #1281
Opened 2023-04-08 11:32 UTC by Decodetalkers

The license used to read everytime when set on that page No I make it read onetime, and storage the message in model

Log: speed up when read license

2023-04-08 11:59 UTC, Decodetalkers commented
这个pr, 让它只在第一次初始化走一次io

2023-04-10 05:14 UTC, BLumia commented on src/plugin-systeminfo/operation/systeminfomodel.cpp
> +void SystemInfoModel::setEnduserAgreement(const QString &text)
```suggestion
void SystemInfoModel::setEndUserAgreement(const QString &text)
```

以及想简写的话可以写成 EULA。上面用 `endAgreement` 以及 `EnduserAgreement` 都有点要全不全要简不简的感觉。

2023-04-10 05:14 UTC, BLumia commented on src/plugin-systeminfo/operation/systeminfomodel.h
> +    std::optional<QString> enduserAgreement() const { return m_endAgreementText; }
同上

2023-04-10 05:14 UTC, BLumia commented on src/plugin-systeminfo/window/utils.h
> +inline QString getEulerEnduserAgreement()
同上

2023-04-10 05:22 UTC, Decodetalkers commented on src/plugin-systeminfo/operation/systeminfomodel.cpp
> +void SystemInfoModel::setEnduserAgreement(const QString &text)
好了

2023-04-10 07:53 UTC, dengbo11 requested changes

2023-04-10 07:53 UTC, dengbo11 commented on src/plugin-systeminfo/operation/systeminfomodel.h
> +    std::optional<QString> endUserAgreement() const { return m_endUserAgreementText; }
可以加上inline

2023-04-10 07:53 UTC, dengbo11 commented on src/plugin-systeminfo/window/utils.h
> +    const QString zhCN_newContent = "/usr/share/protocol/privacy-policy/Privacy-Policy-CN-zh_CN.md";
zhCN_newContent,enUS_newContent 注意命令规范, 改成驼峰命令

2023-04-10 07:53 UTC, dengbo11 commented on src/plugin-systeminfo/window/utils.h
> +        }
`return QFile::exists(bodypath_old) ? getLicenseText(serverEnduserAgreement_old, "") : getLicenseText("/usr/share/deepin-deepinid-client/privacy/End-User-License-Agreement-%1.txt","");`, 下同

2023-04-10 07:53 UTC, dengbo11 commented on src/plugin-systeminfo/window/utils.h
> +    }
改成`zhCN_Content = privacyzhCNFile.exists() ? zhCN_newContent : zhCN_oldContent;`, 下同

2023-04-10 07:53 UTC, dengbo11 commented on src/plugin-systeminfo/window/utils.h
> +            return serverbody;
这种只有一处使用的的值可直接返回(`return getLicenseText(serverEnduserAgreement_new, "");`), 不用去定义一个变量, 下同

2023-04-10 08:10 UTC, Decodetalkers commented on src/plugin-systeminfo/window/utils.h
> +    const QString zhCN_newContent = "/usr/share/protocol/privacy-policy/Privacy-Policy-CN-zh_CN.md";
这个如果驼峰的话就不可读了，我不知道改成什么好

2023-04-10 08:16 UTC, dengbo11 commented on src/plugin-systeminfo/window/utils.h
> +    const QString zhCN_newContent = "/usr/share/protocol/privacy-policy/Privacy-Policy-CN-zh_CN.md";
newCNContent, newEnContent?

2023-04-10 08:38 UTC, Decodetalkers commented on src/plugin-systeminfo/window/utils.h
> +    const QString zhCN_newContent = "/usr/share/protocol/privacy-policy/Privacy-Policy-CN-zh_CN.md";
好

2023-04-10 15:10 UTC, BLumia commented on src/plugin-systeminfo/window/systeminfomodule.cpp
> +    moduleEdition->appendChild(new WidgetModule<VersionProtocolWidget>("gnulicense", tr("gnulicense"), this, &SystemInfoModule::initGnuLicenseModule));
`tr("gnulicense")` 这个没问题吗？

2023-04-10 15:10 UTC, BLumia commented on src/plugin-systeminfo/window/systeminfomodule.cpp
> +    moduleUserAgreement->appendChild(new WidgetModule<UserLicenseWidget>("UserLicense", tr("userlicense"), this, &SystemInfoModule::initUserLicenseModule));
`tr("userlicense")` 这个没问题吗？

2023-04-11 01:30 UTC, dengbo11 commented on src/plugin-systeminfo/window/utils.h
> +    if (DSysInfo::uosType() == DSysInfo::UosType::UosServer) {
超过三个else if, 改用switch case吧

2023-04-11 01:39 UTC, Decodetalkers commented on src/plugin-systeminfo/window/utils.h
> +    if (DSysInfo::uosType() == DSysInfo::UosType::UosServer) {
> 超过三个else if, 改用switch case吧

不行，它不全是判断同一个参数

2023-04-11 01:40 UTC, Decodetalkers commented on src/plugin-systeminfo/window/systeminfomodule.cpp
> +    moduleUserAgreement->appendChild(new WidgetModule<UserLicenseWidget>("UserLicense", tr("userlicense"), this, &SystemInfoModule::initUserLicenseModule));
好,改了，用上面一样的

2023-04-11 02:17 UTC, dengbo11 approved these changes

2023-04-11 02:17 UTC, dengbo11 commented on src/plugin-systeminfo/window/utils.h
> +    if (DSysInfo::uosType() == DSysInfo::UosType::UosServer) {
都是判断的发行版类型吧

2023-04-11 02:26 UTC, merged