feat: add systeminfo message for graphicsplatform
linuxdeepin/dde-control-center pull request #1346
Opened 2023-05-17 05:37 UTC by Decodetalkers

Log:

2023-05-17 06:01 UTC, BLumia requested changes

2023-05-17 06:01 UTC, BLumia commented on src/plugin-systeminfo/window/systeminfomodule.cpp
> +    sysInfoGroup->appendChild(new WidgetModule<TitleValueItem>("graphics", tr("Graphics Platform"), this, &SystemInfoModule::initGraphicsPlatformModule));
需求上，图形平台是和内核版本在一块儿的，图形平台一项在内核版本下面。

2023-05-18 02:35 UTC, BLumia commented on src/plugin-systeminfo/window/systeminfomodule.cpp
> +    sysInfoGroup->appendChild(new WidgetModule<TitleValueItem>("graphics", tr("Graphics Platform"), this, &SystemInfoModule::initGraphicsPlatformModule));
还是没改对，再读下需求：

> 将图形平台与内核版本放置在一起,在信息列表最下方位置进行展示

是这两项放在一起，然后这两项移到最后两项。

2023-05-18 02:39 UTC, BLumia commented on src/plugin-systeminfo/window/systeminfomodule.cpp
> +    item->setValue(XDG_SESSION_TYPE);
考虑走 `QGuiApplication::platformName()` 吧（注意需要把 `xcb` 替换为 `x11`）。一些环境下不一定会设 `XDG_SESSION_TYPE`。

2023-05-18 02:48 UTC, Decodetalkers commented on src/plugin-systeminfo/window/systeminfomodule.cpp
> +    item->setValue(XDG_SESSION_TYPE);
好

2023-05-18 04:43 UTC, BLumia approved these changes

2023-05-18 05:08 UTC, merged