chore: update description of modules
linuxdeepin/dde-control-center pull request #1361
Opened 2023-06-02 02:47 UTC by Decodetalkers

Log: update description of modules

2023-06-02 02:59 UTC, Decodetalkers commented
直接自己翻译了

2023-06-02 05:47 UTC, BLumia requested changes
英文原始文案联系相关人员确认，不要自己来

2023-06-05 08:22 UTC, BLumia requested changes
这里的显示策略可能需要再讨论一下，这个目前的展示行为也有点奇怪。

不过现在的英文文案是肯定不行的。见评注

2023-06-05 08:22 UTC, BLumia commented on src/plugin-defaultapp/window/defappplugin.cpp
> +                  tr("System and Applications Notifications"),
这个是不是改错了？原始是“默认程序”，这个描述是“通知”的。

2023-06-05 08:22 UTC, BLumia commented on src/plugin-display/window/displaymodule.cpp
> +    moduleInterface->setDescription(tr("Monitor settings, multiScreen collaboration and etc"));
暂且不管这个文案哪来的，`multiScreen ` 显然不是正确的写法

2023-06-06 01:49 UTC, BLumia requested changes

2023-06-06 01:49 UTC, BLumia commented on src/frame/pluginmanager.cpp
> +    return QLocale::system().name().toLower().startsWith("zh") ? "、" : ",";
不用判断 QLocal，直接写成 `tr(", ")` 就行，如果觉得会有困惑可以加对应的翻译辅助描述（`tr(", ", "The punctuation symbol, is used to separate items in a list. e.g. A, B, C, D")`）

2023-06-06 02:40 UTC, Decodetalkers commented on src/frame/pluginmanager.cpp
> +    return QLocale::system().name().toLower().startsWith("zh") ? "、" : ",";
好了

2023-06-07 07:13 UTC, BLumia commented on src/frame/pluginmanager.cpp
> +// The punctuation symbol used to separate items in a list. e.g. A, B, C, D")
```suggestion
// The punctuation symbol used to separate items in a list. e.g. A, B, C, D"
```

ps. 译者是看不到代码注释的，双参数的 tr("") 的目的就是确保消歧义提示是译者看得到的。

2023-06-07 07:27 UTC, Decodetalkers commented on src/frame/pluginmanager.cpp
> +// The punctuation symbol used to separate items in a list. e.g. A, B, C, D")
done

2023-06-08 02:45 UTC, BLumia commented on src/plugin-accounts/window/accountsmodule.cpp
> +    : PageModule("accounts", tr("Accounts"), tr("Accounts manager") , QIcon::fromTheme("dcc_nav_accounts"), parent)
我不太确定，这个还用改吗？是不是去掉就行了？如果不是的话，中文原文是”账户管理“的情况下，应该用 management。

2023-06-08 02:48 UTC, Decodetalkers commented on src/plugin-accounts/window/accountsmodule.cpp
> +    : PageModule("accounts", tr("Accounts"), tr("Accounts manager") , QIcon::fromTheme("dcc_nav_accounts"), parent)
给的样式里面是自定义的description,而且它没有子模块

2023-06-09 07:57 UTC, BLumia commented on src/plugin-accounts/window/accountsmodule.cpp
> +    : PageModule("accounts", tr("Accounts"), tr("Accounts management") , QIcon::fromTheme("dcc_nav_accounts"), parent)
```suggestion
    : PageModule("accounts", tr("Accounts"), tr("Account management") , QIcon::fromTheme("dcc_nav_accounts"), parent)
```

2023-06-09 08:03 UTC, Decodetalkers commented on src/plugin-accounts/window/accountsmodule.cpp
> +    : PageModule("accounts", tr("Accounts"), tr("Accounts management") , QIcon::fromTheme("dcc_nav_accounts"), parent)
好了

2023-06-20 01:29 UTC, BLumia approved these changes

2023-06-20 01:32 UTC, Decodetalkers commented
/merge

2023-06-20 01:33 UTC, merged