feat(MousePlugin): enable disabletouchpad anytime
linuxdeepin/dde-control-center pull request #1362
Opened 2023-06-05 03:16 UTC by Decodetalkers

enable user to disable their touchpad if needed

Log:

2023-06-06 08:05 UTC, BLumia commented on src/plugin-mouse/operation/mousedbusproxy.cpp
> +    bool tapEnabled = m_dbusTouchPadProperties->call("Get", TouchpadInterface, "TPadEnable").arguments().at(0).value<QDBusVariant>().variant().toBool();
这个变量名字为什么叫 tapEnabled？

2023-06-06 08:23 UTC, Decodetalkers commented on src/plugin-mouse/operation/mousedbusproxy.cpp
> +    bool tapEnabled = m_dbusTouchPadProperties->call("Get", TouchpadInterface, "TPadEnable").arguments().at(0).value<QDBusVariant>().variant().toBool();
那叫tPadEnabled呢

2023-06-20 01:30 UTC, BLumia commented on src/plugin-mouse/operation/mousedbusproxy.cpp
> +    bool tapEnabled = m_dbusTouchPadProperties->call("Get", TouchpadInterface, "TPadEnable").arguments().at(0).value<QDBusVariant>().variant().toBool();
可以直接写成 `tabletEnabled` 呀，也不长。主要是这里并不是 `tap`，变量名字和实际含义本身是冲突的，所以不合适

2023-06-20 01:30 UTC, BLumia commented on src/plugin-mouse/operation/mousedbusproxy.cpp
> +    bool tPapEnabled = m_dbusTouchPadProperties->call("Get", TouchpadInterface, "TPadEnable").arguments().at(0).value<QDBusVariant>().variant().toBool();
tPap 是什么？touchpad 是一个词，以及是 touchpa**d**

2023-06-21 07:42 UTC, Decodetalkers commented
/integrate

2023-06-25 13:50 UTC, BLumia requested changes
Touchpad 是一个词，不要写成 TouchPad。除评注外的地方也都检查一下。上次提到的误简写为 `tap` 的地方也没改完。

2023-06-25 13:50 UTC, BLumia commented on src/plugin-mouse/operation/mousemodel.cpp
> +    , m_tapEnabled(true)
```suggestion
    , m_touchpadEnabled(true)
```

2023-06-25 13:50 UTC, BLumia commented on src/plugin-mouse/operation/mousedbusproxy.h
> +    void setTouchPadEnabled(bool state);
```suggestion
    void setTouchpadEnabled(bool state);
```

2023-06-26 01:51 UTC, Decodetalkers commented on src/plugin-mouse/operation/mousedbusproxy.h
> +    void setTouchPadEnabled(bool state);
主要是之前也是这样子写的。。我要把原来的也都改了吗

2023-06-26 01:53 UTC, BLumia approved these changes

2023-06-26 01:54 UTC, BLumia commented on src/plugin-mouse/operation/mousedbusproxy.h
> +    void setTouchPadEnabled(bool state);
那先这样，原有的错误拼写回头统一再改吧

2023-06-26 01:56 UTC, Decodetalkers commented
/merge

2023-06-26 01:56 UTC, merged