feat(moduleobject): use struct to describe init
linuxdeepin/dde-control-center pull request #1365
Opened 2023-06-06 10:16 UTC by Decodetalkers

in cpp20, struct can use as AStruct { .name = "ss" }, although this project use 17, but a struct can storage more message, this I think will make it easy to construct a moduleobject

Log: use struct to describe init

2023-06-10 01:24 UTC, Groveer commented
Don't use new feature, special cpp20

2023-06-10 01:32 UTC, justforlxz commented
大概看了一下，貌似用QVariant也能做到optional吧🙈

2023-06-10 02:44 UTC, Decodetalkers commented
> Don't use new feature, special cpp20
只是给用20开发插件的人一个选项而已，我只是觉得用结构体把信息包起来会比较好

2023-06-10 12:02 UTC, 18202781743 commented on include/interface/moduleobject.h
> +    std::optional<QStringList> contentText = std::nullopt;
觉得接口尽量不用新特性，这里只用了这个语法而已，感觉没必要

2023-06-10 12:02 UTC, 18202781743 commented on src/interface/moduleobject.cpp
> +    : QObject(parent)
这里可以直接调用那个构造函数，对于里面的断言，可以放到那个构造函数里，

2023-06-11 16:27 UTC, ComixHe commented on include/interface/moduleobject.h
> +    std::optional<QStringList> contentText = std::nullopt;
感觉直接提供默认值就行，例如这样：
```cpp
struct A{
    QStirng name{"default"};
};
```

2023-06-12 06:18 UTC, Decodetalkers commented
> Don't use new feature, special cpp20

好吧，我想了下，确实只有判空的需求，没必要引入

2023-06-12 09:36 UTC, 18202781743 commented on include/interface/moduleobject.h
> +#include <optional>
？

2023-06-12 10:16 UTC, 18202781743 submitted a review, later dismissed

2023-06-14 02:03 UTC, ComixHe approved these changes

2023-06-14 02:09 UTC, asterwyx approved these changes

2023-06-15 06:40 UTC, justforlxz requested changes

2023-06-15 06:40 UTC, justforlxz commented on include/interface/moduleobject.h
> +struct ModuleObjectMessage
ModuleInitContext

2023-06-15 06:55 UTC, justforlxz requested changes

2023-06-15 06:55 UTC, justforlxz commented on src/interface/moduleobject.cpp
> +#include <QDebug>
删除

2023-06-15 07:13 UTC, justforlxz approved these changes

2023-06-15 08:03 UTC, Decodetalkers commented
/merge

2023-06-15 08:03 UTC, merged