chore(aboutsystem): update translate
linuxdeepin/dde-control-center pull request #1367
Opened 2023-06-08 08:29 UTC by Decodetalkers

Log:

2023-06-08 10:45 UTC, BLumia approved these changes

2023-06-08 11:10 UTC, zsien requested changes

2023-06-08 11:10 UTC, zsien commented on translations/dde-control-center_zh_HK.ts
> +        <translation>協議与私隱政策</translation>
```suggestion
        <translation>協議與私隱政策</translation>
```

2023-06-08 11:10 UTC, zsien commented on translations/dde-control-center_zh_TW.ts
> +        <translation>協議与隱私政策</translation>
同上

2023-06-09 07:08 UTC, Decodetalkers commented
> 繁简转换还是交给 OpenCC 来做吧（

啊，翻译的姐姐没有注意。。她搞错了，我先手动纠正了

2023-06-09 07:12 UTC, zsien approved these changes

2023-06-09 07:12 UTC, merged