fix(systeminfo): on archlinux show unitech
linuxdeepin/dde-control-center pull request #1368
Opened 2023-06-15 06:36 UTC by Decodetalkers

Log:

2023-06-15 06:48 UTC, BLumia requested changes
Commit message: unitech->UnionTech.

`IS_COMMUNITY_SYSTEM` 是构建时打包人员需要主动定义的吗？是的话，是不是这个原本不应该改？

2023-06-15 08:04 UTC, Decodetalkers commented
> Commit message: unitech->UnionTech.
> 
> `IS_COMMUNITY_SYSTEM` 是构建时打包人员需要主动定义的吗？是的话，是不是这个原本不应该改？

是宏啦,头文件的

2023-06-15 08:24 UTC, BLumia commented on src/plugin-systeminfo/window/systeminfomodule.cpp
> +static bool useDeepinCopyRight () {
```suggestion
static bool useDeepinCopyright () {
```

Copyright 是一个词。

2023-06-15 08:24 UTC, BLumia commented on src/plugin-systeminfo/window/systeminfomodule.cpp
> +    static bool useUosLicense = !DSysInfo::isDeepin() || !IS_COMMUNITY_SYSTEM;
这里应该是或？

2023-06-15 08:34 UTC, Decodetalkers commented on src/plugin-systeminfo/window/systeminfomodule.cpp
> +    static bool useUosLicense = !DSysInfo::isDeepin() || !IS_COMMUNITY_SYSTEM;
这里忘记改了

2023-06-16 02:46 UTC, BLumia requested changes

2023-06-16 02:46 UTC, BLumia commented on src/plugin-systeminfo/window/privacypolicywidget.cpp
> +    static bool useDeepinLicense = !DSysInfo::isDeepin() || IS_COMMUNITY_SYSTEM;
如果不是 deepin 或者 是社区版系统？

2023-06-16 03:14 UTC, Decodetalkers commented on src/plugin-systeminfo/window/privacypolicywidget.cpp
> +    static bool useDeepinLicense = !DSysInfo::isDeepin() || IS_COMMUNITY_SYSTEM;
那改成notUseUosLicense呢

2023-06-16 03:47 UTC, BLumia commented on src/plugin-systeminfo/window/privacypolicywidget.cpp
> +    static bool useDeepinLicense = !DSysInfo::isDeepin() || IS_COMMUNITY_SYSTEM;
你可以用文字描述一下你想表达的原始逻辑吗？为什么“**不是** deepin”属于“使用 deepin 许可证”的条件之一？

2023-06-16 03:49 UTC, BLumia commented on src/plugin-systeminfo/window/privacypolicywidget.cpp
> +    static bool useDeepinLicense = !DSysInfo::isDeepin() || IS_COMMUNITY_SYSTEM;
哦，看了下 dtkcore，isDeepin 是判断 `productType() == Deepin || productType() == Uos`，那说得通了。感觉这个 dtk 接口的语义上有问题。

2023-06-16 03:50 UTC, BLumia submitted a review, later dismissed

2023-06-16 04:33 UTC, wineee requested changes

2023-06-16 04:33 UTC, wineee commented on src/plugin-systeminfo/window/privacypolicywidget.cpp
> +    static bool useDeepinLicense = !DSysInfo::isDeepin() || IS_COMMUNITY_SYSTEM;
\brief Check current distro is Deepin or not.
 \note Uos will also return true.

不能用 DSysInfo::isDeepin 区分 deepin 和 uos

2023-06-16 04:36 UTC, wineee commented on src/plugin-systeminfo/window/privacypolicywidget.cpp
> +    static bool useDeepinLicense = !DSysInfo::isDeepin() || IS_COMMUNITY_SYSTEM;
DSysInfo::ProductType  可以区分 deepin/uos

2023-06-16 05:16 UTC, BLumia commented on src/plugin-systeminfo/window/privacypolicywidget.cpp
> +    static bool useDeepinLicense = !DSysInfo::isDeepin() || IS_COMMUNITY_SYSTEM;
这里不是在用它区分 deepin 和 uos 吧，这里是如果不是 deepin 也不是 UOS 的情况，或者是“社区版系统”的清空下。

我觉得这个 isDeepin 的语义太容易导致误解代码实际作用了。

2023-06-16 05:28 UTC, Decodetalkers commented on src/plugin-systeminfo/window/privacypolicywidget.cpp
> +    static bool useDeepinLicense = !DSysInfo::isDeepin() || IS_COMMUNITY_SYSTEM;
done.，这个判断可以直接解决需求

2023-06-16 06:36 UTC, wineee approved these changes

2023-06-19 01:43 UTC, BLumia approved these changes

2023-06-19 02:07 UTC, Decodetalkers commented
/recheck

2023-06-19 02:28 UTC, Decodetalkers commented
/recheck

2023-06-19 09:23 UTC, Decodetalkers commented
/merge

2023-06-19 09:24 UTC, merged