feat(datetime): region set
linuxdeepin/dde-control-center pull request #1384
Opened 2023-07-07 02:56 UTC by Decodetalkers

Log: support region set

2023-07-07 03:47 UTC, BLumia commented on src/plugin-datetime/operation/datetimedbusproxy.cpp
>      QDBusInterface dbus("org.deepin.dde.LangSelector1", "/org/deepin/dde/LangSelector1", "org.deepin.dde.LangSelector1", QDBusConnection::sessionBus());
这里应该用上你定义的几个 const string 吧

2023-07-07 03:47 UTC, BLumia commented on src/plugin-datetime/operation/datetimedbusproxy.cpp
> +const static QString LangSelectorInterface = "org.deepin.dde.LangSelector1";
没必要加 static 吧，QStringLiteral 就够了。

2023-07-07 03:47 UTC, BLumia commented on src/plugin-datetime/operation/datetimedbusproxy.cpp
> +        qDebug() << "it is error"<< reply.error();
这个 it is error 要么改的更有描述性，要么删掉。

2023-07-07 03:47 UTC, BLumia commented on src/plugin-datetime/operation/datetimedbusproxy.cpp
> +        qDebug() << "it is error"<< reply.error();
同

2023-07-07 03:47 UTC, BLumia commented on src/plugin-datetime/window/zoneanddatemodule.cpp
这个 zone 是想表达什么，区域吗？区域的话应该用 region

2023-07-07 03:47 UTC, BLumia commented on src/plugin-datetime/window/zoneanddatemodule.cpp
> +    : PageModule("zoneanddate", tr("Zone and Format"), parent)
同文件名的评注，以及这个文案是谁提供的？

2023-07-07 03:47 UTC, BLumia commented on src/plugin-datetime/window/zoneanddatemodule.cpp
> +    appendChild(new ItemModule("LocaleSet", tr("Locale Set")));
文案找产品核对，下同。

2023-07-07 03:47 UTC, BLumia commented on src/plugin-datetime/window/zoneanddatemodule.cpp
> +constexpr int SHOW_NUMBER = 123456789;
没必要单独拿出来定义吧，就用了一次

2023-07-07 03:47 UTC, BLumia commented on src/plugin-datetime/operation/datetimedbusproxy.h
> +    friend const QDataStream &operator>>(QDataStream &ds, LocaleInfo &info)
cppcheck

2023-07-07 03:47 UTC, BLumia commented on src/plugin-datetime/window/widgets/region_setting_dialog.cpp
> +constexpr int SHOW_NUMBER = 123456789;
同

2023-07-07 03:48 UTC, Decodetalkers commented on src/plugin-datetime/operation/datetimedbusproxy.h
> +    friend const QDataStream &operator>>(QDataStream &ds, LocaleInfo &info)
这个是检查错了

2023-07-07 03:54 UTC, Decodetalkers commented on src/plugin-datetime/window/zoneanddatemodule.cpp
这个是文档里面的名字，zone and Format

2023-07-08 04:21 UTC, BLumia requested changes

2023-07-08 04:21 UTC, BLumia commented on src/plugin-datetime/operation/datetimedbusproxy.cpp
> +        qDebug() << "Canot get localeRegion: "<< reply.error();
```suggestion
        qDebug() << "Can not get localeRegion: "<< reply.error();
```

2023-07-08 04:21 UTC, BLumia commented on src/plugin-datetime/operation/datetimedbusproxy.cpp
> +        qDebug() << "Canot get localeRegion: "<< reply.error();
```suggestion
        qDebug() << "Can not get localeRegion: "<< reply.error();
```

2023-07-08 04:21 UTC, BLumia commented on src/plugin-datetime/operation/datetimedbusproxy.cpp
> +    if(reply.value().isEmpty()) {
```suggestion
    if (reply.value().isEmpty()) {
```

2023-07-08 04:21 UTC, BLumia commented on src/plugin-datetime/window/zoneanddatemodule.cpp
好，我下周和提供文案的人核对一下这个问题。我先标个 request change 避免我遗漏掉这件事。

2023-07-11 05:21 UTC, BLumia commented on src/plugin-datetime/operation/datetimedbusproxy.cpp
> +        qDebug() << "Ca nnot get localeRegion: "<< reply.error();
你不能从一种错误写法改成另一种错误写法啊...

2023-07-11 05:21 UTC, BLumia commented on src/plugin-datetime/window/regionanddatemodule.cpp
> +    center->addWidget(new InforShowUnit(tr("Date And Time"), currentDateAndTime), 0, 2, 1, 2);
```suggestion
    center->addWidget(new InforShowUnit(tr("Date and Time"), currentDateAndTime), 0, 2, 1, 2);
```

2023-07-11 05:23 UTC, BLumia commented on src/plugin-datetime/window/regionanddatemodule.cpp
> +    appendChild(new ItemModule("LocaleSet", tr("Locale Set")));
这里的原始中文文案是什么？

2023-07-11 05:24 UTC, Decodetalkers commented on src/plugin-datetime/window/regionanddatemodule.cpp
> +    appendChild(new ItemModule("LocaleSet", tr("Locale Set")));
地区设置

2023-07-11 05:52 UTC, BLumia commented on src/plugin-datetime/window/regionanddatemodule.cpp
> +    appendChild(new ItemModule("LocaleSet", tr("Locale Set")));
如果是这个设置模块的名称的话，叫 `Regional Settings` 可能更合适。这里表示名称肯定不能用 "Set"

2023-07-11 07:38 UTC, BLumia approved these changes

2023-07-14 06:10 UTC, Decodetalkers commented
/merge

2023-07-14 06:11 UTC, merged