chore: support linglong update
linuxdeepin/dde-control-center pull request #1411
Opened 2023-08-30 06:59 UTC by Decodetalkers

Log:

2023-08-30 07:07 UTC, black-desk commented on src/plugin-update/operation/updatework.cpp
> +        systemdcommand = QStringList{ "--user", "disable", "-now", LINGLONG_SERVICE };
disable do not have --now argument

2023-08-30 07:09 UTC, black-desk requested changes
-

2023-08-31 08:28 UTC, Decodetalkers commented
/integrate

2023-09-01 08:23 UTC, Decodetalkers commented
/integrate

2023-09-01 08:31 UTC, Decodetalkers commented
/integrate

2023-09-04 05:58 UTC, Decodetalkers commented
/integrate

2023-09-05 02:57 UTC, black-desk requested changes

2023-09-05 02:57 UTC, black-desk commented on src/plugin-update/operation/updatemodel.cpp
> +    Q_EMIT longlongAutoUpdateChanged(m_linglongAutoUpdateActived);
先检查值是否真的发生变化再发信号

2023-09-05 02:57 UTC, black-desk commented on src/plugin-update/operation/updatework.cpp
> +    process.waitForFinished();
@BLumia 这个似乎会在ui线程里调用 你看看行不行.

2023-09-05 02:57 UTC, black-desk commented on src/plugin-update/window/updatesettingsmodule.cpp
> +            tr(""),
@BLumia 这个留空么?

2023-09-05 07:21 UTC, BLumia commented on src/plugin-update/window/updatesettingsmodule.cpp
> +            tr(""),
留空就不用 tr() 了

2023-09-05 07:23 UTC, BLumia commented on src/plugin-update/operation/updatework.cpp
> +    process.waitForFinished();
这里实际会卡多久？不是太久的话能接受。

2023-09-05 07:29 UTC, Decodetalkers commented on src/plugin-update/operation/updatework.cpp
> +    process.waitForFinished();
哦,这个是需要阻塞的。看了下，它是在active时候检查的

2023-09-06 01:55 UTC, BLumia commented on src/plugin-update/window/updatesettingsmodule.cpp
> +                        "If there is update for linglong package, system will update it for you"));
linglong 需要写成 Linglong 吗？ @black-desk

2023-09-06 02:00 UTC, black-desk commented on src/plugin-update/window/updatesettingsmodule.cpp
> +                        "If there is update for linglong package, system will update it for you"));
不

2023-09-06 02:07 UTC, BLumia approved these changes

2023-09-06 02:07 UTC, merged