fix: wrong cn translation
linuxdeepin/dde-control-center pull request #1443
Opened 2023-09-19 02:42 UTC by Decodetalkers

Issue: https://github.com/linuxdeepin/developer-center/issues/5694 Log:

2023-09-20 01:20 UTC, BLumia approved these changes

2023-09-25 02:28 UTC, Decodetalkers commented
/check obs

2023-09-25 07:33 UTC, Decodetalkers commented
/merge

2023-09-25 08:23 UTC, Decodetalkers commented
/check obs

2023-09-26 01:46 UTC, BLumia requested changes

2023-09-26 01:46 UTC, BLumia commented on translations/dde-control-center_zh_CN.ts
> +        <translation>您还没有上传过头像，可点击或拖曳上传图片</translation>
刚意识到，拖“拽”写错了吧，

2023-09-26 01:48 UTC, Decodetalkers commented on translations/dde-control-center_zh_CN.ts
> +        <translation>您还没有上传过头像，可点击或拖曳上传图片</translation>
哦，我平常用拖曳就

2023-09-26 01:54 UTC, BLumia approved these changes

2023-09-26 02:19 UTC, Decodetalkers commented
/merge

2023-09-26 02:19 UTC, merged