Newam
linuxdeepin/dde-control-center pull request #1474
Opened 2023-10-31 09:53 UTC by Decodetalkers

2023-11-06 09:14 UTC, Decodetalkers commented
/check obs

2023-11-07 07:36 UTC, Decodetalkers commented
- https://github.com/linuxdeepin/developer-center/issues/6108

2023-11-09 05:07 UTC, Decodetalkers commented
- https://github.com/linuxdeepin/developer-center/issues/6138

2023-11-13 06:44 UTC, ComixHe requested changes

2023-11-13 06:44 UTC, ComixHe commented on src/plugin-defaultapp/operation/mimedbusproxy.cpp
> -    connect(m_mimeInter, SIGNAL(Change()), this, SIGNAL(Change()), Qt::QueuedConnection);
这个信号为什么废弃了？

2023-11-13 06:44 UTC, ComixHe commented on src/plugin-defaultapp/operation/mimedbusproxy.cpp
> +void MimeDBusProxy::DeleteUserApp([[maybe_unused]] const QString &desktopId)
如果这些接口没用了不能直接删掉吗？

2023-11-13 07:20 UTC, ComixHe commented on src/plugin-defaultapp/operation/defappworker.cpp
> +    for (App app : systemList) {
TODO

2023-11-13 07:21 UTC, Decodetalkers commented on src/plugin-defaultapp/operation/mimedbusproxy.cpp
> -    connect(m_mimeInter, SIGNAL(Change()), this, SIGNAL(Change()), Qt::QueuedConnection);
新的am没有这个啊

2023-11-13 07:25 UTC, ComixHe approved these changes

2023-11-13 07:53 UTC, Decodetalkers commented
/merge

2023-11-13 07:54 UTC, merged