chore: Tweak UI to adapt to sidebar blur
linuxdeepin/dde-control-center pull request #1577
Opened 2024-01-30 09:06 UTC by FeiWang1119

tweak UI to adapt to sidebar blur

Log:

2024-01-30 09:19 UTC, Decodetalkers submitted a review, later dismissed

2024-01-31 01:45 UTC, FeiWang1119 commented
/topic sidebar

2024-01-31 01:47 UTC, FeiWang1119 commented
/integr-topic sidebar

2024-01-31 03:39 UTC, Decodetalkers commented
/integr-topic sidebar

2024-01-31 05:56 UTC, kegechen requested changes

2024-01-31 05:56 UTC, kegechen commented on src/frame/listitemdelegate.cpp
> +        painter->setOpacity(0.5);
0.7

2024-01-31 05:58 UTC, FeiWang1119 commented
/integr-topic sidebar

2024-01-31 06:04 UTC, kegechen submitted a review, later dismissed

2024-01-31 06:16 UTC, FeiWang1119 commented on src/frame/listitemdelegate.cpp
> +        painter->setOpacity(0.5);
done

2024-01-31 06:16 UTC, FeiWang1119 commented
/integr-topic sidebar

2024-01-31 06:22 UTC, FeiWang1119 commented
/integr-topic sidebar

2024-02-01 02:35 UTC, FeiWang1119 commented
/integr-topic sidebar

2024-02-01 06:10 UTC, kegechen approved these changes

2024-02-01 06:11 UTC, merged