chore: compatible to new dock
linuxdeepin/dde-control-center pull request #1645
Opened 2024-07-05 03:00 UTC by FeiWang1119

pass the paths of icons instead of the pixmap of icons

Log:

2024-07-05 06:39 UTC, FeiWang1119 commented
![截图_选择区域_20240705143814](https://github.com/linuxdeepin/dde-control-center/assets/102005754/95c698c3-e2ac-457b-ad87-bee32a78d624)
![截图_选择区域_20240705143649](https://github.com/linuxdeepin/dde-control-center/assets/102005754/27c2e247-ef60-402b-8577-7823ea49fe90)

2024-07-08 02:11 UTC, kegechen commented on src/plugin-personalization-dock/window/dockplugin.cpp
> +    auto originPixmap = QIcon(dccIcon).pixmap(ICON_SIZE, ICON_SIZE);
`QIcon(dccIcon)` 这种方式能行吗

2024-07-08 02:14 UTC, kegechen commented on src/plugin-personalization-dock/window/dockplugin.cpp
> +        color.setAlpha(0.4 * 255);
```suggestion
    color = palette.windowText().color(isDeactivate?QColor::Inactive : QColor::Active, ...);

```

2024-07-08 02:27 UTC, FeiWang1119 commented on src/plugin-personalization-dock/window/dockplugin.cpp
> +    auto originPixmap = QIcon(dccIcon).pixmap(ICON_SIZE, ICON_SIZE);
dccIcon 全路径

2024-07-08 02:28 UTC, FeiWang1119 commented on src/plugin-personalization-dock/window/dockplugin.cpp
> +        color.setAlpha(0.4 * 255);
done

2024-07-08 02:35 UTC, kegechen approved these changes

2024-07-08 02:42 UTC, kegechen requested changes
集成 dde-shell 时一起带上这个

2024-07-08 05:29 UTC, FeiWang1119 commented
/topic shell-tray-loader

2024-07-09 09:13 UTC, kegechen commented
/help

2024-07-09 09:13 UTC, kegechen commented
/approved

2024-07-10 00:22 UTC, kegechen approved these changes

2024-07-15 03:07 UTC, FeiWang1119 commented
/integr-topic shell-tray-loader

2024-07-15 06:06 UTC, merged