fix: typo 'wapper' => 'wrapper'
linuxdeepin/dde-control-center pull request #350
Opened 2021-03-09 03:39 UTC by cheese

fix typo 'wapper' => 'wrapper'

Log: fix typo 'wapper' => 'wrapper'
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>

2021-03-09 03:40 UTC, deepinAdmin reviewed
Patch Set 1:

代码注释率

2021-03-09 03:40 UTC, deepinAdmin reviewed
Patch Set 1:

commit check success!

2021-03-09 03:40 UTC, deepinAdmin reviewed
Patch Set 1:

cppcheck success!

2022-04-24 02:15 UTC, shenwenqi3441 requested changes

2022-04-24 02:15 UTC, shenwenqi3441 commented on CMakeLists.txt
> -install(FILES dde-control-center-wapper DESTINATION bin PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
这个会影响单元测试的调用，请查看其他所有调用位置一并修改

2022-04-24 02:36 UTC, cheese commented
不继续推送这个修改，将错就错对下游没影响

2022-04-24 02:36 UTC, closed without merging